site_name: SNUAILAB Waffle
repo_url: https://github.com/snuailab/waffle_hub
repo_name: snuailab/waffle_hub

theme:
  name: material
  logo: assets/waffle_icon_gray.png
  favicon: assets/waffle_icon.png
  palette:
    primary: orange
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - autorefs
  - mkdocstrings
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/snuailab/waffle

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/snuailab/mycompany/

    - icon: fontawesome/brands/medium
      link: https://medium.com/snuailab

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: README.md
  - Tutorials:
    - Introduction: tutorials/README.md
    - Dataset: 
      - tutorials/dataset/README.md
      - Import: tutorials/dataset/import.ipynb
      - Split: tutorials/dataset/split.ipynb
      - Export: tutorials/dataset/export.ipynb
    - Hub:
      - tutorials/hub/README.md
      - Create: tutorials/hub/create.ipynb
      - Train: tutorials/hub/train.ipynb
      # - Test: tutorials/hub/test.ipynb
      - Export: tutorials/hub/export.ipynb
    - Menu:
      - tutorials/menu/README.md
  - Documentations:
    - Waffle Hub:
      - Introduction: waffle_hub/README.md
      - Dataset:
        - Dataset: waffle_hub/dataset/dataset.md
        - Field: waffle_hub/dataset/field.md
      - Hub:
        - Hub: waffle_hub/hub/hub.md
        - Result: waffle_hub/hub/result.md
        - Configuration: waffle_hub/hub/configuration.md
    - Waffle Menu:
      - Introduction: waffle_menu/README.md
      - Active Learning: waffle_menu/active_learning.md
  - Blog: https://medium.com/snuailab