FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++ wget

ENV OMP_NUM_THREADS=1
ENV MKL_SERVICE_FORCE_INTEL=1

# Install Python packages (no cache)
ARG NO_CACHE_ARG

WORKDIR /workspace
COPY . ./app
RUN pip install -U pip \
    && pip install -r app/requirements.txt \
    && pip install -U numpy

ENTRYPOINT python -m streamlit run app/main.py --server.port $WAFFLE_APP_PORT --server.fileWatcherType none
